image: python:3.8-alpine

pages:
  script:
    - apt-get update && apt -y install graphviz
    - pip install -r requirements.txt
    - mkdocs build
  artifacts:
    paths:
      - public/
  only:
    - main


