site_name: Grassroots Economics Documentation
site_url: https://docs.grassecon.org
nav:
  - Karibu: index.md
  - Community:
      - Intro: community/index.md
      - Charter: community/charter.md
      - Contribution Guidelines: community/contrib.md
      - Code of Conduct: community/conduct.md
      - Roadmap: community/roadmap.md
  - Operations:
      - Intro: ops/index.md
      - Logical Framework: ops/log_frame.md
      - Program Toolkit: ops/pqt.md
      - Voucher Creation: ops/voucher.md
      - Team Guide: ops/team_guide.md
      - Stakeholder Guide: ops/local_stakeholders.md
      - Humanitarian Support: ops/support.md
  - Commons:
      - Intro: commons/index.md
      - Commons Template: commons/template.md
      - Commons Agreement: commons/agreement.md
      - Voucher Agreement: commons/voucher.md
      - Service Agreement: commons/service.md
      - PATH License: commons/path.md
      - Data Policy: commons/data_policy.md
      - Child Protection Policy: commons/child_policy.md
  - Cyber:
      - Intro: cyber/index.md
      - Software: https://software.grassecon.org/
      - Pooling Guide: cyber/pool-guide.md
      - Staking Guide: cyber/staking-guide.md
  - Education:
      - Intro: edu/index.md
      - Glossary: edu/glossary.md
      - FAQ: edu/faq.md
      - Quiz: https://forms.gle/yJfVKsZUS1Tdmmmc9
      - Training Guide: edu/training.md
      - Case Study: edu/case_study.md
      - MOOC: https://www.grassrootseconomics.org/pages/mooc.html

repo_url: https://github.com/grassrootseconomics/docs.grassecon.org
repo_name: grassrootseconomics/docs
edit_uri: -/tree/main/docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    primary: green
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
#readthedocs
site_dir: public
markdown_extensions:
  - attr_list
  - mkdocs_graphviz
  - toc:
      permalink: true

extra_css:
  - assets/style.css

extra:
  generator: false

plugins:
  - git-revision-date
  - search
