site_name: Grassroots Economics Documentation
site_url: https://example.com
nav:
  - General:
      - Karibu: index.md
      - FAQ: faq.md
      - Glossary: glossary.md
      - Roadmap: roadmap.md
  - Community:
      - Charter: charter.md
      - Contribution Guidelines: contrib.md
      - Code of Conduct: conduct.md
  - Operations:
      - Intro: ops.md
      - Training:
          - Case Study: case_study.md
          - Training Guide: training.md
      - Legal:
          - Clearing Union: sarafu_clearing_union.md
          - Service Provider: scu_member_csp.md
          - General Member: scu_member_group.md
          - Service Agreement: scu_intermember.md
          - Data Policy: data_policy.md
  - Software:
      - CIC Stack: cic_stack.md
      - Design Principles: principles.md

repo_url: https://gitlab.com/grassrootseconomics/grassrootseconomics.gitlab.io
repo_name: grassrootseconomics/docs
edit_uri: -/tree/main/docs
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    primary: green
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
#readthedocs
site_dir: public
markdown_extensions:
  - mkdocs_graphviz
  - toc:
      permalink: true

extra:
  generator: false

plugins:
  - git-revision-date
  - search
