site_name: Grassroots Economics Documentation
site_url: https://example.com
nav:
  - General:
      - Karibu: index.md
      - FAQ: faq.md
      - Glossary: glossary.md
      - Roadmap: roadmap.md
  - Community:
      - Charter: community/index.md
      - Contribution Guidelines: community/contrib.md
      - Code of Conduct: community/conduct.md
  - Operations:
      - Intro: operations/index.md
      - Case Study: operations/case_study.md
      - Training Guide: operations/training.md
      - Team Guide: operations/team_guide.md
      - Logical Framework: operations/log_frame.md
      - Stakeholder Guide: operations/local_stakeholders.md
  - Legal:
      - Intro: legal/index.md
      - GE Commons License: legal/gecl1.md
      - Sarafu Clearing Union: legal/scu.md
      - Voucher Creation: legal/scu_voucher.md
      - Service Agreement: legal/scu_service.md
      - Data Policy: legal/data_policy.md
  - Software:
      - CIC Stack: software/index.md
      - Design Principles: software/principles.md

repo_url: https://gitlab.com/grassrootseconomics/grassrootseconomics.gitlab.io
repo_name: grassrootseconomics/docs
edit_uri: -/tree/main/docs
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    primary: green
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
#readthedocs
site_dir: public
markdown_extensions:
  - mkdocs_graphviz
  - toc:
      permalink: true

extra:
  generator: false

plugins:
  - git-revision-date
  - search
