site_name: Grassroots Economics Documentation
site_url: https://example.com
nav:
  - Home: index.md
  - CIC Operations:
      - CIC Ops: cic_ops.md
      - Training Guide:
          - CIC Training Guide: cic_training.md
      - Legal Structures:
          - Sarafu Clearing Union (SCU): sarafu_clearing_union.md
          - SCU Member (CSP): scu_member_csp.md
          - SCU Member (Group): scu_member_group.md
          - SCU Intermember agreement): scu_intermember.md
  - CIC Software Stack:
      - CIC Stack: cic_stack.md
  - Roadmap: road_map.md
theme: readthedocs
site_dir: public
