name: Pelican site CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        CUSTOM_DOMAIN: docs.grassecon.org
        EXTRA_PACKAGES: graphviz